<?php
$blogPostCollection = $block->getCollection();
$config = $block->getConfigDetails();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$helper = $objectManager->create('AHT\Blog\Helper\Data');
$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');

?>
<div class="ahtblog-post-main">
    <?php
    if ($blogPostCollection->getSize() > 0) : ?>
        <ul class="ahtblog-post-listing-main">
            <?php foreach ($blogPostCollection as $data) : ?>
                <?php
                $imagePath = '';
                $postData = $data->getData();
                $imageData = json_decode($postData['image']);
                if (empty($imageData)) {
                    $imagePath = $imageHelper->init($blogPostCollection, 'product_base_image')->constrainOnly(FALSE)
                        ->keepAspectRatio(TRUE)
                        ->keepFrame(FALSE)
                        ->getUrl();;
                } else {
                    foreach ($imageData as $img) {
                        $imgArr = (array)$img;
                        $imagePath = $imgArr['url'];
                    }
                }
                ?>
                <li class="ahtblog-post-listing">
                    <div class="ahtblog-post-list">
                        <div class="ahtblog-post-list-image">
                            <a class="post-title" href="<?php echo $this->getUrl('ahtblog/post/view',
                                ['id' => $data->getId()]) ?>">
                            <img src="<?= $imagePath;?>" alt="post-img" class="ahtblog-post-listing-image">
                            </a>
                        </div>
                        <div class="ahtblog-post-list-main-content">
                            <h2 class="aht-post-heading">
                                <a class="post-title" href="<?php echo $this->getUrl('ahtblog/post/view',
                                    ['id' => $data->getId()]) ?>">
                                    <?php echo $data->getTitle();?>
                                </a>
                            </h2>
                            <span class="label date">
                            <i class="fa fa-calendar" aria-hidden="true"></i>
                                <?php
                                $dateStr = strtotime($data->getPublishedAt());
                                echo date('d-M-Y', $dateStr);
                                ?>
                            </span>
                            <span class="blog-post-author">
                            <i class="fa fa-user" aria-hidden="true"></i>
                                <?= $helper->getPostAuthor($data['author']);?>
                            </span>
                            <div class="ahtblog-post-content">
                                <?php echo $data->getShortContent(); ?>
                            </div>
                            <a class="action primary readmore" href="<?php echo $this->getUrl('ahtblog/post/view',
                                ['id' => $data->getId()]) ?>">Read more</a>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
        <div style="clear: both"></div>
        <div class="toolbar-bottom">
            <div class="toolbar bottom">
                <?php echo $block->getPagerHtml(); ?>
            </div>
        </div>
    <?php else : ?>
        <p class="message notice"><?php echo __('No blog post available.') ?></p>
    <?php endif; ?>
</div>